{
 "title": "MLT Erroring Endpoints",
 "tags": [
  "intro-to-mlt",
  "wallet"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "query": {
     "query": "label_values(traces_spanmetrics_calls_total{span_kind=\"SPAN_KIND_SERVER\",http_target!~\"/debug/pprof.*\"}, http_target)\n"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Error rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_calls_total{span_kind=\"SPAN_KIND_SERVER\",http_target!~\"/debug/pprof.*\",status_code=\"STATUS_CODE_ERROR\",http_target=~\"$endpoint\"}[1m])) by (http_target)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(traces_spanmetrics_latency_bucket{span_kind=\"SPAN_KIND_SERVER\",http_target!~\"/debug/pprof.*\",status_code=\"STATUS_CODE_ERROR\",http_target=~\"$endpoint\"}[1m])) by (http_target, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Root Cause: Errors",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "limit": 20,
     "query": "{ span.http.target =~ \"$endpoint\" && kind = server} >> { status = error } | select(span.db.name, span.db.statement)"
    }
   ]
  }
 ]
}