service_name: "wallet"

log:
  url: "http://alloy:3100/loki/api/v1/push"

rest_server:
  listen_address: "0.0.0.0"
  port: "4848"
  read_timeout: "5s"
  write_timeout: "10s"

jwt:
  signing_key: "secret"
  signing_method: "HS256"
  issuer: "test-local"

otel:
  endpoint: "alloy:4317"
  use_prometheus: true

db:
  dsn: "postgres://local:supersecret@wallet-database:5432/wallet?sslmode=disable"
  max_conn: 10
  min_conn: 0
  max_conn_lifetime: "1h"
  max_conn_idle_time: "30m"
  health_check_period: "1m"
  conn_timeout: "5s"
